baseURL = 'silewis.dev'
title = "Silewis37's Blog"
copyright = "© 2024 - Silewis or Silewis - This work is licensed under a <a href='https://creativecommons.org/licenses/by-nc-nd/4.0/' rel='license'>Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>."
canonifyurls = true
languageCode = "en-US"
paginate = 3
theme = "hugo-dusk"

googleAnalytics = ""
disqusShortname = ""

[params.author]
  name = "Silewis"
  intro = """\
  I am a up and coming software developer with tons of experience in python programming and machine learning capabilities.
   \
  """

SectionPagesMenu = "main"

[taxonomies]
  archive = "archive"
  blog = "blog"
  category = "categories"
  series = "series"
  tag = "tags"
  about = 'about'
  friends = "friends"
# Configure syntax highlight
[markup]
  [markup.highlight]
    style = "gruvbox"  # dark themes: monokai, api, fruity, native, rrt, swapoff ... https://xyproto.github.io/splash/docs/longer/all.html

[[menu.main]]
  name = "About"
  weight = -130
  identifier = "about"
  url = "/about"

[[menu.submenu]]
  name = "About2"
  weight = -130
  identifier = "about2"
  url = "/about2"
  
[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/blog/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "Friends"
  weight = -140
  identifier = "friends"
  url = "/friends"

[params.meta]
  keywords = "blog, tech, hacking, rev, web, pwn, ctf, ai, personal assistant, machine learning"
  description = "Silewis37's Blog"

[params]
  mainSections = ['blog']
  theme_colors = "cold-dark" # uses color css file under static/css/default-dark.css
  enable_separate_main_page = false # enable a separate main page with author intro and recent posts instead of the list of posts
  utterancesRepo="REPO_NAME" # Utterances is enabled when this param is set
  utterancesTheme="github-dark" # Default: github-dark
  utterancesIssueTerm="pathname" # Default: pathname

[markup.goldmark.renderer]
  unsafe = true


